// src/createAgent.ts
import { AgentEngine, CreateAgentOptions } from "@agentxjs/types/agent";
var createAgent = [
  "/**\\n* Create an AgentEngine instance\\n*/",
  "\\n",
  "declare",
  " ",
  "function",
  " ",
  createAgent,
  "(",
  "options",
  ":",
  " ",
  CreateAgentOptions,
  ")",
  ":",
  " ",
  AgentEngine,
  ";",
];
// src/AgentStateMachine.ts
import { AgentState, StateChangeHandler, Unsubscribe, AgentOutput } from "@agentxjs/types/agent";
var AgentStateMachine = [
  "/**\\n* AgentStateMachine implementation\\n*/",
  "\\n",
  "declare",
  " ",
  "class",
  " ",
  AgentStateMachine,
  " ",
  "{",
  "\\n\\t",
  "private",
  " ",
  "_state",
  ";",
  "\\n\\t",
  "private",
  " ",
  "readonly",
  " ",
  "handlers",
  ";",
  "\\n\\t",
  "/**\\n\\t* Current agent state\\n\\t*/",
  "\\n\\t",
  "get",
  " ",
  "state",
  "(",
  ")",
  ":",
  " ",
  AgentState,
  ";",
  "\\n\\t",
  "/**\\n\\t* Process an event and update internal state if it's a StateEvent\\n\\t*\\n\\t* @param event - Event from MealyMachine (could be any AgentOutput)\\n\\t*/",
  "\\n\\t",
  "process",
  "(",
  "event",
  ":",
  " ",
  AgentOutput,
  ")",
  ":",
  " ",
  "void",
  ";",
  "\\n\\t",
  "/**\\n\\t* Subscribe to state changes\\n\\t*\\n\\t* @param handler - Callback receiving { prev, current } state change\\n\\t* @returns Unsubscribe function\\n\\t*/",
  "\\n\\t",
  onStateChange,
  "(",
  "handler",
  ":",
  " ",
  StateChangeHandler,
  ")",
  ":",
  " ",
  Unsubscribe,
  ";",
  "\\n\\t",
  "/**\\n\\t* Reset state machine (used on destroy)\\n\\t*/",
  "\\n\\t",
  "reset",
  "(",
  ")",
  ":",
  " ",
  "void",
  ";",
  "\\n\\t",
  "/**\\n\\t* Map StateEvent type to AgentState\\n\\t*\\n\\t* @param event - StateEvent from MealyMachine\\n\\t* @returns New AgentState or null if no transition needed\\n\\t*/",
  "\\n\\t",
  "private",
  " ",
  mapEventToState,
  ";",
  "\\n\\t",
  "/**\\n\\t* Notify all registered handlers of state change\\n\\t*/",
  "\\n\\t",
  "private",
  " ",
  notifyHandlers,
  ";",
  "\\n",
  "}",
];

// src/index.ts
import {
  AgentEngine as AgentEngine2,
  CreateAgentOptions as CreateAgentOptions2,
} from "@agentxjs/types/agent";

// src/engine/MealyMachine.ts
import { AgentOutput as AgentOutput2, StreamEvent } from "@agentxjs/types/agent";
var MealyMachine = [
  "/**\\n* MealyMachine - Pure Mealy Machine for event processing\\n*\\n* - Input: StreamEvent (from Driver)\\n* - Output: AgentOutput[] (state, message, turn events)\\n* - State: Managed internally per agentId\\n*/",
  "\\n",
  "declare",
  " ",
  "class",
  " ",
  MealyMachine,
  " ",
  "{",
  "\\n\\t",
  "private",
  " ",
  "readonly",
  " ",
  "store",
  ";",
  "\\n\\t",
  "constructor",
  "(",
  ")",
  ";",
  "\\n\\t",
  "/**\\n\\t* Process a single driveable event and return output events\\n\\t*\\n\\t* This is the core Mealy Machine operation:\\n\\t* process(agentId, event) → outputs[]\\n\\t*\\n\\t* @param agentId - The agent identifier (for state isolation)\\n\\t* @param event - StreamEvent to process\\n\\t* @returns Array of output events (state, message, turn events)\\n\\t*/",
  "\\n\\t",
  "process",
  "(",
  agentId,
  ":",
  " ",
  "string",
  ",",
  " ",
  "event",
  ":",
  " ",
  StreamEvent,
  ")",
  ":",
  " ",
  AgentOutput2,
  "[",
  "]",
  ";",
  "\\n\\t",
  "/**\\n\\t* Process chained events recursively\\n\\t*\\n\\t* Some processors produce events that trigger other processors:\\n\\t* - MessageAssembler produces MessageEvents\\n\\t* - TurnTracker consumes MessageEvents to produce TurnEvents\\n\\t*/",
  "\\n\\t",
  "private",
  " ",
  processChained,
  ";",
  "\\n\\t",
  "/**\\n\\t* Clear state for an agent\\n\\t*\\n\\t* Call this when an agent is destroyed to free memory.\\n\\t*/",
  "\\n\\t",
  clearState,
  "(",
  agentId,
  ":",
  " ",
  "string",
  ")",
  ":",
  " ",
  "void",
  ";",
  "\\n\\t",
  "/**\\n\\t* Check if state exists for an agent\\n\\t*/",
  "\\n\\t",
  hasState,
  "(",
  agentId,
  ":",
  " ",
  "string",
  ")",
  ":",
  " ",
  "boolean",
  ";",
  "\\n",
  "}",
];
var createMealyMachine = [
  "/**\\n* Factory function to create MealyMachine\\n*/",
  "\\n",
  "declare",
  " ",
  "function",
  " ",
  createMealyMachine,
  "(",
  ")",
  ":",
  " ",
  MealyMachine,
  ";",
];
// src/engine/mealy/Source.ts
var Source = [
  "/**\\n* Source - Input adapter for Mealy Machine\\n*\\n* A Source transforms external requests into internal events.\\n* This is a pure function type - lifecycle management belongs to higher layers.\\n*\\n* Pattern: (request) => AsyncIterable<input>\\n*\\n* @template TInput - The event type produced for Processors\\n* @template TRequest - The request type received from external (default: void)\\n*\\n* @example\\n* ```typescript\\n* // Simple source (no request)\\n* const timerSource: Source<TimerEvent> = async function* () {\\n*   while (true) {\\n*     yield { type: 'tick', timestamp: Date.now() };\\n*     await sleep(1000);\\n*   }\\n* };\\n*\\n* // Source with request\\n* const apiSource: Source<ApiEvent, ApiRequest> = async function* (request) {\\n*   const response = await fetch(request.url);\\n*   yield { type: 'response', data: await response.json() };\\n* };\\n* ```\\n*/",
  "\\n",
  "type",
  " ",
  Source,
  "<",
  "\\n\\t",
  TInput,
  ",",
  "\\n\\t",
  TRequest,
  " ",
  "=",
  " ",
  "void",
  "\\n",
  ">",
  " ",
  "=",
  " ",
  "(",
  "request",
  ":",
  " ",
  TRequest,
  ")",
  " ",
  "=>",
  " ",
  AsyncIterable,
  "<",
  TInput,
  ">",
  ";",
];
var SourceDefinition = [
  "/**\\n* SourceDefinition - Named Source with metadata\\n*\\n* Use this when you need to identify sources by name.\\n*/",
  "\\n",
  "interface",
  " ",
  SourceDefinition,
  "<",
  "\\n\\t",
  TInput,
  ",",
  "\\n\\t",
  TRequest,
  " ",
  "=",
  " ",
  "void",
  "\\n",
  ">",
  " ",
  "{",
  "\\n\\t",
  "/**\\n\\t* Unique name for this source\\n\\t*/",
  "\\n\\t",
  "name",
  ":",
  " ",
  "string",
  ";",
  "\\n\\t",
  "/**\\n\\t* Optional description\\n\\t*/",
  "\\n\\t",
  "description",
  "?",
  ":",
  " ",
  "string",
  ";",
  "\\n\\t",
  "/**\\n\\t* The source function\\n\\t*/",
  "\\n\\t",
  "source",
  ":",
  " ",
  Source,
  "<",
  TInput,
  ",",
  " ",
  TRequest,
  ">",
  ";",
  "\\n",
  "}",
];
// src/engine/mealy/Processor.ts
var Processor = [
  "/**\\n* Processor - Core pure function type for stream processing\\n*\\n* A Processor is a pure function that takes a state and an input,\\n* and returns a new state along with outputs.\\n*\\n* Pattern: (state, input) => [newState, outputs]\\n*\\n* Key properties:\\n* - Pure function (no side effects)\\n* - Deterministic (same input → same output)\\n* - State is a means (accumulator), outputs are the goal\\n*\\n* @template TState - The state type (internal accumulator)\\n* @template TInput - The input type\\n* @template TOutput - The output type (emissions)\\n*\\n* @example\\n* ```typescript\\n* const messageProcessor: Processor<MsgState, StreamEvent, MsgEvent> =\\n*   (state, input) => {\\n*     switch (input.type) {\\n*       case 'text_delta':\\n*         return [{ ...state, buffer: state.buffer + input.data.text }, []];\\n*       case 'message_stop':\\n*         return [{ buffer: '' }, [{ type: 'assistant_message', content: state.buffer }]];\\n*       default:\\n*         return [state, []];\\n*     }\\n*   };\\n* ```\\n*/",
  "\\n",
  "type",
  " ",
  Processor,
  "<",
  "\\n\\t",
  TState,
  ",",
  "\\n\\t",
  TInput,
  ",",
  "\\n\\t",
  TOutput,
  "\\n",
  ">",
  " ",
  "=",
  " ",
  "(",
  "state",
  ":",
  " ",
  Readonly,
  "<",
  TState,
  ">",
  ",",
  " ",
  "input",
  ":",
  " ",
  TInput,
  ")",
  " ",
  "=>",
  " ",
  "[",
  TState,
  ",",
  " ",
  TOutput,
  "[",
  "]",
  "]",
  ";",
];
var ProcessorResult = [
  "/**\\n* ProcessorResult - The return type of a Processor\\n*\\n* A tuple containing:\\n* - [0] newState: The updated state after processing\\n* - [1] outputs: Array of outputs to emit\\n*/",
  "\\n",
  "type",
  " ",
  ProcessorResult,
  "<",
  "\\n\\t",
  TState,
  ",",
  "\\n\\t",
  TOutput,
  "\\n",
  ">",
  " ",
  "=",
  " ",
  "[",
  TState,
  ",",
  " ",
  TOutput,
  "[",
  "]",
  "]",
  ";",
];
var ProcessorDefinition = [
  "/**\\n* ProcessorDefinition - Metadata for a Processor\\n*/",
  "\\n",
  "interface",
  " ",
  ProcessorDefinition,
  "<",
  "\\n\\t",
  TState,
  ",",
  "\\n\\t",
  TInput,
  ",",
  "\\n\\t",
  TOutput,
  "\\n",
  ">",
  " ",
  "{",
  "\\n\\t",
  "/**\\n\\t* Unique name for this processor\\n\\t*/",
  "\\n\\t",
  "name",
  ":",
  " ",
  "string",
  ";",
  "\\n\\t",
  "/**\\n\\t* The pure processor function\\n\\t*/",
  "\\n\\t",
  "processor",
  ":",
  " ",
  Processor,
  "<",
  TState,
  ",",
  " ",
  TInput,
  ",",
  " ",
  TOutput,
  ">",
  ";",
  "\\n\\t",
  "/**\\n\\t* Initial state factory\\n\\t*/",
  "\\n\\t",
  initialState,
  ":",
  " ",
  "(",
  ")",
  " ",
  "=>",
  " ",
  TState,
  ";",
  "\\n\\t",
  "/**\\n\\t* Optional description\\n\\t*/",
  "\\n\\t",
  "description",
  "?",
  ":",
  " ",
  "string",
  ";",
  "\\n",
  "}",
];
// src/engine/mealy/Sink.ts
var Sink = [
  "/**\\n* Sink - Output adapter for Mealy Machine\\n*\\n* A Sink receives outputs from Processors and produces external effects.\\n* This is a pure function type - lifecycle management belongs to higher layers.\\n*\\n* Pattern: (id, outputs) => void | Promise<void>\\n*\\n* @template TOutput - The output type received from Processors\\n*\\n* @example\\n* ```typescript\\n* // Sync sink (logging)\\n* const logSink: Sink<AgentEvent> = (id, outputs) => {\\n*   outputs.forEach(output => console.log(`[${id}]`, output));\\n* };\\n*\\n* // Async sink (network)\\n* const sseSink: Sink<AgentEvent> = async (id, outputs) => {\\n*   for (const output of outputs) {\\n*     await sseConnection.send(id, output);\\n*   }\\n* };\\n* ```\\n*/",
  "\\n",
  "type",
  " ",
  Sink,
  "<",
  TOutput,
  ">",
  " ",
  "=",
  " ",
  "(",
  "id",
  ":",
  " ",
  "string",
  ",",
  " ",
  "outputs",
  ":",
  " ",
  TOutput,
  "[",
  "]",
  ")",
  " ",
  "=>",
  " ",
  "void",
  " ",
  "|",
  " ",
  Promise,
  "<",
  "void",
  ">",
  ";",
];
var SinkDefinition = [
  "/**\\n* SinkDefinition - Named Sink with metadata\\n*\\n* Use this when you need to identify sinks by name.\\n*/",
  "\\n",
  "interface",
  " ",
  SinkDefinition,
  "<",
  TOutput,
  ">",
  " ",
  "{",
  "\\n\\t",
  "/**\\n\\t* Unique name for this sink\\n\\t*/",
  "\\n\\t",
  "name",
  ":",
  " ",
  "string",
  ";",
  "\\n\\t",
  "/**\\n\\t* Optional description\\n\\t*/",
  "\\n\\t",
  "description",
  "?",
  ":",
  " ",
  "string",
  ";",
  "\\n\\t",
  "/**\\n\\t* Optional filter to select which outputs to process\\n\\t*\\n\\t* If not provided, all outputs are processed.\\n\\t* Return true to process the output, false to skip.\\n\\t*/",
  "\\n\\t",
  "filter",
  "?",
  ":",
  " ",
  "(",
  "output",
  ":",
  " ",
  TOutput,
  ")",
  " ",
  "=>",
  " ",
  "boolean",
  ";",
  "\\n\\t",
  "/**\\n\\t* The sink function\\n\\t*/",
  "\\n\\t",
  "sink",
  ":",
  " ",
  Sink,
  "<",
  TOutput,
  ">",
  ";",
  "\\n",
  "}",
];
// src/engine/mealy/Store.ts
var Store = [
  "/**\\n* Store - State storage interface for stream processing\\n*\\n* A Store abstracts state persistence, allowing processors to be stateless\\n* while maintaining state externally.\\n*\\n* @template T - The state type to store\\n*\\n* @example\\n* ```typescript\\n* const store = new MemoryStore<AgentState>();\\n* store.set('agent_123', { count: 0 });\\n* const state = store.get('agent_123');\\n* ```\\n*/",
  "\\n",
  "interface",
  " ",
  Store,
  "<",
  T,
  ">",
  " ",
  "{",
  "\\n\\t",
  "/**\\n\\t* Get state by ID\\n\\t* @param id - Unique identifier (e.g., agentId, sessionId)\\n\\t* @returns The stored state or undefined if not found\\n\\t*/",
  "\\n\\t",
  "get",
  "(",
  "id",
  ":",
  " ",
  "string",
  ")",
  ":",
  " ",
  T,
  " ",
  "|",
  " ",
  "undefined",
  ";",
  "\\n\\t",
  "/**\\n\\t* Set state for an ID\\n\\t* @param id - Unique identifier\\n\\t* @param state - The state to store\\n\\t*/",
  "\\n\\t",
  "set",
  "(",
  "id",
  ":",
  " ",
  "string",
  ",",
  " ",
  "state",
  ":",
  " ",
  T,
  ")",
  ":",
  " ",
  "void",
  ";",
  "\\n\\t",
  "/**\\n\\t* Delete state for an ID\\n\\t* @param id - Unique identifier\\n\\t*/",
  "\\n\\t",
  "delete",
  "(",
  "id",
  ":",
  " ",
  "string",
  ")",
  ":",
  " ",
  "void",
  ";",
  "\\n\\t",
  "/**\\n\\t* Check if state exists for an ID\\n\\t* @param id - Unique identifier\\n\\t* @returns True if state exists\\n\\t*/",
  "\\n\\t",
  "has",
  "(",
  "id",
  ":",
  " ",
  "string",
  ")",
  ":",
  " ",
  "boolean",
  ";",
  "\\n",
  "}",
];
var MemoryStore = [
  "/**\\n* MemoryStore - In-memory implementation of Store\\n*\\n* Stores state in a Map. Suitable for development and single-process deployments.\\n* For production multi-process scenarios, use RedisStore or PostgresStore.\\n*\\n* @template T - The state type to store\\n*\\n* @example\\n* ```typescript\\n* const store = new MemoryStore<MyState>();\\n* store.set('session_1', { count: 0 });\\n* ```\\n*/",
  "\\n",
  "declare",
  " ",
  "class",
  " ",
  MemoryStore,
  "<",
  T,
  ">",
  " ",
  "implements",
  " ",
  Store,
  "<",
  T,
  ">",
  " ",
  "{",
  "\\n\\t",
  "private",
  " ",
  "states",
  ";",
  "\\n\\t",
  "get",
  "(",
  "id",
  ":",
  " ",
  "string",
  ")",
  ":",
  " ",
  T,
  " ",
  "|",
  " ",
  "undefined",
  ";",
  "\\n\\t",
  "set",
  "(",
  "id",
  ":",
  " ",
  "string",
  ",",
  " ",
  "state",
  ":",
  " ",
  T,
  ")",
  ":",
  " ",
  "void",
  ";",
  "\\n\\t",
  "delete",
  "(",
  "id",
  ":",
  " ",
  "string",
  ")",
  ":",
  " ",
  "void",
  ";",
  "\\n\\t",
  "has",
  "(",
  "id",
  ":",
  " ",
  "string",
  ")",
  ":",
  " ",
  "boolean",
  ";",
  "\\n\\t",
  "/**\\n\\t* Clear all stored states\\n\\t*/",
  "\\n\\t",
  "clear",
  "(",
  ")",
  ":",
  " ",
  "void",
  ";",
  "\\n\\t",
  "/**\\n\\t* Get the number of stored states\\n\\t*/",
  "\\n\\t",
  "get",
  " ",
  "size",
  "(",
  ")",
  ":",
  " ",
  "number",
  ";",
  "\\n\\t",
  "/**\\n\\t* Get all stored IDs\\n\\t*/",
  "\\n\\t",
  "keys",
  "(",
  ")",
  ":",
  " ",
  IterableIterator,
  "<",
  "string",
  ">",
  ";",
  "\\n",
  "}",
];
// src/engine/mealy/Mealy.ts
var MealyConfig = [
  "/**\\n* MealyConfig - Configuration for creating a Mealy instance\\n*/",
  "\\n",
  "interface",
  " ",
  MealyConfig,
  "<",
  "\\n\\t",
  TState,
  ",",
  "\\n\\t",
  TInput,
  "\\n",
  ">",
  " ",
  "{",
  "\\n\\t",
  "/**\\n\\t* The processor function to execute (pure Mealy transition function)\\n\\t*/",
  "\\n\\t",
  "processor",
  ":",
  " ",
  Processor,
  "<",
  TState,
  ",",
  " ",
  TInput,
  ",",
  " ",
  TInput,
  ">",
  ";",
  "\\n\\t",
  "/**\\n\\t* The store for state persistence\\n\\t*/",
  "\\n\\t",
  "store",
  ":",
  " ",
  Store,
  "<",
  TState,
  ">",
  ";",
  "\\n\\t",
  "/**\\n\\t* Initial state for new IDs\\n\\t*/",
  "\\n\\t",
  initialState,
  ":",
  " ",
  TState,
  ";",
  "\\n\\t",
  "/**\\n\\t* Sinks to receive outputs\\n\\t* Can be simple Sink functions or SinkDefinitions with filter/name\\n\\t*/",
  "\\n\\t",
  "sinks",
  "?",
  ":",
  " ",
  "(",
  Sink,
  "<",
  TInput,
  ">",
  " ",
  "|",
  " ",
  SinkDefinition,
  "<",
  TInput,
  ">",
  ")",
  "[",
  "]",
  ";",
  "\\n\\t",
  "/**\\n\\t* Whether to recursively process outputs\\n\\t* If true, outputs are fed back into the processor\\n\\t*\\n\\t* @default true\\n\\t*/",
  "\\n\\t",
  "recursive",
  "?",
  ":",
  " ",
  "boolean",
  ";",
  "\\n\\t",
  "/**\\n\\t* Maximum recursion depth to prevent infinite loops\\n\\t*\\n\\t* @default 100\\n\\t*/",
  "\\n\\t",
  maxDepth,
  "?",
  ":",
  " ",
  "number",
  ";",
  "\\n",
  "}",
];
var ProcessResult = [
  "/**\\n* ProcessResult - Result of processing an input\\n*/",
  "\\n",
  "interface",
  " ",
  ProcessResult,
  "<",
  "\\n\\t",
  TState,
  ",",
  "\\n\\t",
  TOutput,
  "\\n",
  ">",
  " ",
  "{",
  "\\n\\t",
  "/**\\n\\t* The new state after processing\\n\\t*/",
  "\\n\\t",
  "state",
  ":",
  " ",
  TState,
  ";",
  "\\n\\t",
  "/**\\n\\t* All outputs produced (including from recursion)\\n\\t*/",
  "\\n\\t",
  "outputs",
  ":",
  " ",
  TOutput,
  "[",
  "]",
  ";",
  "\\n\\t",
  "/**\\n\\t* Number of processor invocations (including recursion)\\n\\t*/",
  "\\n\\t",
  processCount,
  ":",
  " ",
  "number",
  ";",
  "\\n",
  "}",
];
var Mealy = [
  "/**\\n* Mealy - Mealy Machine runtime\\n*\\n* Implements the Mealy Machine pattern: (state, input) => (state, output)\\n* where output depends on both current state and input.\\n*/",
  "\\n",
  "declare",
  " ",
  "class",
  " ",
  Mealy,
  "<",
  "\\n\\t",
  TState,
  ",",
  "\\n\\t",
  TInput,
  "\\n",
  ">",
  " ",
  "{",
  "\\n\\t",
  "private",
  " ",
  "readonly",
  " ",
  "processor",
  ";",
  "\\n\\t",
  "private",
  " ",
  "readonly",
  " ",
  "store",
  ";",
  "\\n\\t",
  "private",
  " ",
  "readonly",
  " ",
  initialState,
  ";",
  "\\n\\t",
  "private",
  " ",
  "readonly",
  " ",
  "sinks",
  ";",
  "\\n\\t",
  "private",
  " ",
  "readonly",
  " ",
  "recursive",
  ";",
  "\\n\\t",
  "private",
  " ",
  "readonly",
  " ",
  maxDepth,
  ";",
  "\\n\\t",
  "constructor",
  "(",
  "config",
  ":",
  " ",
  MealyConfig,
  "<",
  TState,
  ",",
  " ",
  TInput,
  ">",
  ")",
  ";",
  "\\n\\t",
  "/**\\n\\t* Process an input through the Mealy Machine\\n\\t*\\n\\t* @param id - Unique identifier (e.g., agentId)\\n\\t* @param input - The input to process\\n\\t* @returns Result containing new state and all outputs\\n\\t*/",
  "\\n\\t",
  "process",
  "(",
  "id",
  ":",
  " ",
  "string",
  ",",
  " ",
  "input",
  ":",
  " ",
  TInput,
  ")",
  ":",
  " ",
  ProcessResult,
  "<",
  TState,
  ",",
  " ",
  TInput,
  ">",
  ";",
  "\\n\\t",
  "/**\\n\\t* Internal process with depth tracking\\n\\t*/",
  "\\n\\t",
  "private",
  " ",
  processInternal,
  ";",
  "\\n\\t",
  "/**\\n\\t* Send outputs to all sinks\\n\\t*/",
  "\\n\\t",
  "private",
  " ",
  sendToSinks,
  ";",
  "\\n\\t",
  "/**\\n\\t* Get current state for an ID (without processing)\\n\\t*/",
  "\\n\\t",
  getState,
  "(",
  "id",
  ":",
  " ",
  "string",
  ")",
  ":",
  " ",
  TState,
  " ",
  "|",
  " ",
  "undefined",
  ";",
  "\\n\\t",
  "/**\\n\\t* Check if state exists for an ID\\n\\t*/",
  "\\n\\t",
  hasState,
  "(",
  "id",
  ":",
  " ",
  "string",
  ")",
  ":",
  " ",
  "boolean",
  ";",
  "\\n\\t",
  "/**\\n\\t* Delete state for an ID (cleanup)\\n\\t*/",
  "\\n\\t",
  "cleanup",
  "(",
  "id",
  ":",
  " ",
  "string",
  ")",
  ":",
  " ",
  "void",
  ";",
  "\\n\\t",
  "/**\\n\\t* Add a sink at runtime\\n\\t*/",
  "\\n\\t",
  addSink,
  "(",
  "sink",
  ":",
  " ",
  Sink,
  "<",
  TInput,
  ">",
  " ",
  "|",
  " ",
  SinkDefinition,
  "<",
  TInput,
  ">",
  ")",
  ":",
  " ",
  "void",
  ";",
  "\\n\\t",
  "/**\\n\\t* Remove a sink by name (only works for SinkDefinitions)\\n\\t*/",
  "\\n\\t",
  removeSink,
  "(",
  "name",
  ":",
  " ",
  "string",
  ")",
  ":",
  " ",
  "boolean",
  ";",
  "\\n",
  "}",
];
var createMealy = [
  "/**\\n* createMealy - Factory function for creating Mealy Machine instances\\n*\\n* @example\\n* ```typescript\\n* const mealy = createMealy({\\n*   processor: myProcessor,\\n*   store: new MemoryStore(),\\n*   initialState: { count: 0 },\\n*   sinks: [logSink],\\n* });\\n* ```\\n*/",
  "\\n",
  "declare",
  " ",
  "function",
  " ",
  createMealy,
  "<",
  "\\n\\t",
  TState,
  ",",
  "\\n\\t",
  TInput,
  "\\n",
  ">",
  "(",
  "config",
  ":",
  " ",
  MealyConfig,
  "<",
  TState,
  ",",
  " ",
  TInput,
  ">",
  ")",
  ":",
  " ",
  Mealy,
  "<",
  TState,
  ",",
  " ",
  TInput,
  ">",
  ";",
];
// src/engine/mealy/combinators.ts
var combineProcessors = [
  "/**\\n* combineProcessors - Combine multiple processors into one\\n*\\n* Each sub-processor manages its own slice of state.\\n* All processors receive the same event and their outputs are merged.\\n*\\n* @example\\n* ```typescript\\n* interface CombinedState {\\n*   message: MessageState;\\n*   state: StateMachineState;\\n*   turn: TurnState;\\n* }\\n*\\n* const combinedProcessor = combineProcessors<CombinedState, Event, Event>({\\n*   message: messageProcessor,\\n*   state: stateMachineProcessor,\\n*   turn: turnTrackerProcessor,\\n* });\\n* ```\\n*/",
  "\\n",
  "declare",
  " ",
  "function",
  " ",
  combineProcessors,
  "<",
  "\\n\\t",
  TState,
  " ",
  "extends",
  " ",
  Record,
  "<",
  "string",
  ",",
  " ",
  "unknown",
  ">",
  ",",
  "\\n\\t",
  TInput,
  ",",
  "\\n\\t",
  TOutput,
  "\\n",
  ">",
  "(",
  "processors",
  ":",
  " ",
  "{",
  " ",
  "[",
  K,
  " ",
  "in",
  " ",
  "keyof",
  " ",
  TState,
  "]",
  " ",
  ":",
  " ",
  Processor,
  "<",
  TState,
  "[",
  K,
  "]",
  ",",
  " ",
  TInput,
  ",",
  " ",
  TOutput,
  ">",
  " ",
  "}",
  ")",
  ":",
  " ",
  Processor,
  "<",
  TState,
  ",",
  " ",
  TInput,
  ",",
  " ",
  TOutput,
  ">",
  ";",
];
var combineInitialStates = [
  "/**\\n* combineInitialStates - Helper to create initial state for combined processors\\n*/",
  "\\n",
  "declare",
  " ",
  "function",
  " ",
  combineInitialStates,
  "<",
  TState,
  " ",
  "extends",
  " ",
  Record,
  "<",
  "string",
  ",",
  " ",
  "unknown",
  ">",
  ">",
  "(",
  initialStates,
  ":",
  " ",
  "{",
  " ",
  "[",
  K,
  " ",
  "in",
  " ",
  "keyof",
  " ",
  TState,
  "]",
  " ",
  ":",
  " ",
  "(",
  ")",
  " ",
  "=>",
  " ",
  TState,
  "[",
  K,
  "]",
  " ",
  "}",
  ")",
  ":",
  " ",
  "(",
  ")",
  " ",
  "=>",
  " ",
  TState,
  ";",
];
var chainProcessors = [
  "/**\\n* chainProcessors - Chain processors where output of one feeds into the next\\n*\\n* Useful for layered event processing:\\n* Stream Events → Message Events → Turn Events\\n*\\n* @example\\n* ```typescript\\n* const pipeline = chainProcessors(\\n*   streamToMessageProcessor,\\n*   messageToTurnProcessor,\\n* );\\n* ```\\n*/",
  "\\n",
  "declare",
  " ",
  "function",
  " ",
  chainProcessors,
  "<",
  "\\n\\t",
  TState,
  ",",
  "\\n\\t",
  TEvent,
  "\\n",
  ">",
  "(",
  ".",
  ".",
  ".",
  "processors",
  ":",
  " ",
  Processor,
  "<",
  TState,
  ",",
  " ",
  TEvent,
  ",",
  " ",
  TEvent,
  ">",
  "[",
  "]",
  ")",
  ":",
  " ",
  Processor,
  "<",
  TState,
  ",",
  " ",
  TEvent,
  ",",
  " ",
  TEvent,
  ">",
  ";",
];
var filterProcessor = [
  "/**\\n* filterProcessor - Create a processor that only processes certain events\\n*\\n* @example\\n* ```typescript\\n* const textOnlyProcessor = filterProcessor(\\n*   (event) => event.type === 'text_delta',\\n*   textProcessor,\\n* );\\n* ```\\n*/",
  "\\n",
  "declare",
  " ",
  "function",
  " ",
  filterProcessor,
  "<",
  "\\n\\t",
  TState,
  ",",
  "\\n\\t",
  TInput,
  ",",
  "\\n\\t",
  TOutput,
  "\\n",
  ">",
  "(",
  "predicate",
  ":",
  " ",
  "(",
  "event",
  ":",
  " ",
  TInput,
  ")",
  " ",
  "=>",
  " ",
  "boolean",
  ",",
  " ",
  "processor",
  ":",
  " ",
  Processor,
  "<",
  TState,
  ",",
  " ",
  TInput,
  ",",
  " ",
  TOutput,
  ">",
  ")",
  ":",
  " ",
  Processor,
  "<",
  TState,
  ",",
  " ",
  TInput,
  ",",
  " ",
  TOutput,
  ">",
  ";",
];
var mapOutput = [
  "/**\\n* mapOutput - Transform output events\\n*\\n* @example\\n* ```typescript\\n* const withTimestamp = mapOutput(\\n*   myProcessor,\\n*   (output) => ({ ...output, processedAt: Date.now() }),\\n* );\\n* ```\\n*/",
  "\\n",
  "declare",
  " ",
  "function",
  " ",
  mapOutput,
  "<",
  "\\n\\t",
  TState,
  ",",
  "\\n\\t",
  TInput,
  ",",
  "\\n\\t",
  TOutput,
  ",",
  "\\n\\t",
  TMapped,
  "\\n",
  ">",
  "(",
  "processor",
  ":",
  " ",
  Processor,
  "<",
  TState,
  ",",
  " ",
  TInput,
  ",",
  " ",
  TOutput,
  ">",
  ",",
  " ",
  "mapper",
  ":",
  " ",
  "(",
  "output",
  ":",
  " ",
  TOutput,
  ")",
  " ",
  "=>",
  " ",
  TMapped,
  ")",
  ":",
  " ",
  Processor,
  "<",
  TState,
  ",",
  " ",
  TInput,
  ",",
  " ",
  TMapped,
  ">",
  ";",
];
var withLogging = [
  "/**\\n* withLogging - Add logging to a processor (for debugging)\\n*\\n* @example\\n* ```typescript\\n* const debugProcessor = withLogging(myProcessor, 'MyProcessor');\\n* ```\\n*/",
  "\\n",
  "declare",
  " ",
  "function",
  " ",
  withLogging,
  "<",
  "\\n\\t",
  TState,
  ",",
  "\\n\\t",
  TInput,
  ",",
  "\\n\\t",
  TOutput,
  "\\n",
  ">",
  "(",
  "processor",
  ":",
  " ",
  Processor,
  "<",
  TState,
  ",",
  " ",
  TInput,
  ",",
  " ",
  TOutput,
  ">",
  ",",
  " ",
  "name",
  ":",
  " ",
  "string",
  ",",
  " ",
  "logger",
  "?",
  ":",
  " ",
  "{",
  "\\n\\t",
  "debug",
  ":",
  " ",
  "(",
  "message",
  ":",
  " ",
  "string",
  ",",
  " ",
  "data",
  "?",
  ":",
  " ",
  "unknown",
  ")",
  " ",
  "=>",
  " ",
  "void",
  "\\n",
  "}",
  ")",
  ":",
  " ",
  Processor,
  "<",
  TState,
  ",",
  " ",
  TInput,
  ",",
  " ",
  TOutput,
  ">",
  ";",
];
var identityProcessor = [
  "/**\\n* identityProcessor - A processor that does nothing (useful as default)\\n*/",
  "\\n",
  "declare",
  " ",
  "function",
  " ",
  identityProcessor,
  "<",
  "\\n\\t",
  TState,
  ",",
  "\\n\\t",
  TEvent,
  "\\n",
  ">",
  "(",
  ")",
  ":",
  " ",
  Processor,
  "<",
  TState,
  ",",
  " ",
  TEvent,
  ",",
  " ",
  TEvent,
  ">",
  ";",
];
// src/engine/internal/messageAssemblerProcessor.ts
import {
  StreamEvent as StreamEvent2,
  AssistantMessageEvent,
  ToolCallMessageEvent,
  ToolResultMessageEvent,
  ErrorMessageEvent,
} from "@agentxjs/types/agent";
var PendingContent = [
  "/**\\n* Pending content accumulator\\n*/",
  "\\n",
  "interface",
  " ",
  PendingContent,
  " ",
  "{",
  "\\n\\t",
  "type",
  ":",
  " ",
  '"text"',
  " ",
  "|",
  " ",
  '"tool_use"',
  ";",
  "\\n\\t",
  "index",
  ":",
  " ",
  "number",
  ";",
  "\\n\\t",
  textDeltas,
  "?",
  ":",
  " ",
  "string",
  "[",
  "]",
  ";",
  "\\n\\t",
  toolId,
  "?",
  ":",
  " ",
  "string",
  ";",
  "\\n\\t",
  toolName,
  "?",
  ":",
  " ",
  "string",
  ";",
  "\\n\\t",
  toolInputJson,
  "?",
  ":",
  " ",
  "string",
  ";",
  "\\n",
  "}",
];
var PendingToolCall = [
  "/**\\n* Pending tool call info (for matching with tool_result)\\n*/",
  "\\n",
  "interface",
  " ",
  PendingToolCall,
  " ",
  "{",
  "\\n\\t",
  "id",
  ":",
  " ",
  "string",
  ";",
  "\\n\\t",
  "name",
  ":",
  " ",
  "string",
  ";",
  "\\n",
  "}",
];
var MessageAssemblerState = [
  "/**\\n* MessageAssemblerState\\n*\\n* Tracks the state of message assembly from stream events.\\n*/",
  "\\n",
  "interface",
  " ",
  MessageAssemblerState,
  " ",
  "{",
  "\\n\\t",
  "/**\\n\\t* Current message ID being assembled\\n\\t*/",
  "\\n\\t",
  currentMessageId,
  ":",
  " ",
  "string",
  " ",
  "|",
  " ",
  "null",
  ";",
  "\\n\\t",
  "/**\\n\\t* Timestamp when the current message started\\n\\t*/",
  "\\n\\t",
  messageStartTime,
  ":",
  " ",
  "number",
  " ",
  "|",
  " ",
  "null",
  ";",
  "\\n\\t",
  "/**\\n\\t* Pending content blocks being accumulated\\n\\t* Key is the content block index\\n\\t*/",
  "\\n\\t",
  pendingContents,
  ":",
  " ",
  Record,
  "<",
  "number",
  ",",
  " ",
  PendingContent,
  ">",
  ";",
  "\\n\\t",
  "/**\\n\\t* Pending tool calls waiting for results\\n\\t* Key is the tool call ID\\n\\t*/",
  "\\n\\t",
  pendingToolCalls,
  ":",
  " ",
  Record,
  "<",
  "string",
  ",",
  " ",
  PendingToolCall,
  ">",
  ";",
  "\\n",
  "}",
];
var createInitialMessageAssemblerState = [
  "/**\\n* Initial state factory for MessageAssembler\\n*/",
  "\\n",
  "declare",
  " ",
  "function",
  " ",
  createInitialMessageAssemblerState,
  "(",
  ")",
  ":",
  " ",
  MessageAssemblerState,
  ";",
];
var MessageAssemblerOutput = [
  "/**\\n* Output event types from MessageAssembler\\n*/",
  "\\n",
  "type",
  " ",
  MessageAssemblerOutput,
  " ",
  "=",
  " ",
  AssistantMessageEvent,
  " ",
  "|",
  " ",
  ToolCallMessageEvent,
  " ",
  "|",
  " ",
  ToolResultMessageEvent,
  " ",
  "|",
  " ",
  ErrorMessageEvent,
  ";",
];
var MessageAssemblerInput = [
  "/**\\n* Input event types for MessageAssembler\\n*/",
  "\\n",
  "type",
  " ",
  MessageAssemblerInput,
  " ",
  "=",
  " ",
  StreamEvent2,
  ";",
];
var messageAssemblerProcessor = [
  "/**\\n* messageAssemblerProcessor\\n*\\n* Pure Mealy transition function for message assembly.\\n* Pattern: (state, input) => [newState, outputs]\\n*/",
  "\\n",
  "declare",
  " ",
  "const",
  " ",
  messageAssemblerProcessor,
  ":",
  " ",
  Processor,
  "<",
  MessageAssemblerState,
  ",",
  " ",
  MessageAssemblerInput,
  ",",
  " ",
  MessageAssemblerOutput,
  ">",
  ";",
];
var messageAssemblerProcessorDef = [
  "/**\\n* MessageAssembler Processor Definition\\n*/",
  "\\n",
  "declare",
  " ",
  "const",
  " ",
  messageAssemblerProcessorDef,
  ":",
  " ",
  ProcessorDefinition,
  "<",
  MessageAssemblerState,
  ",",
  " ",
  MessageAssemblerInput,
  ",",
  " ",
  MessageAssemblerOutput,
  ">",
  ";",
];
// src/engine/internal/stateEventProcessor.ts
import {
  StreamEvent as StreamEvent3,
  ConversationStartEvent,
  ConversationRespondingEvent,
  ConversationEndEvent,
  ConversationInterruptedEvent,
  ToolPlannedEvent,
  ToolExecutingEvent,
  ErrorOccurredEvent,
} from "@agentxjs/types/agent";
var StateEventProcessorContext = [
  "/**\\n* StateEventProcessorContext\\n*\\n* Minimal context needed for event transformation logic.\\n* Does NOT track agent state - only auxiliary info for decision-making.\\n*\\n* Currently empty - no context needed as all information comes from events.\\n*/",
  "\\n",
  "interface",
  " ",
  StateEventProcessorContext,
  " ",
  "{",
  "}",
];
var createInitialStateEventProcessorContext = [
  "/**\\n* Initial context factory for StateEventProcessor\\n*/",
  "\\n",
  "declare",
  " ",
  "function",
  " ",
  createInitialStateEventProcessorContext,
  "(",
  ")",
  ":",
  " ",
  StateEventProcessorContext,
  ";",
];
var StateEventProcessorOutput = [
  "/**\\n* Output event types from StateEventProcessor\\n*/",
  "\\n",
  "type",
  " ",
  StateEventProcessorOutput,
  " ",
  "=",
  " ",
  ConversationStartEvent,
  " ",
  "|",
  " ",
  ConversationRespondingEvent,
  " ",
  "|",
  " ",
  ConversationEndEvent,
  " ",
  "|",
  " ",
  ConversationInterruptedEvent,
  " ",
  "|",
  " ",
  ToolPlannedEvent,
  " ",
  "|",
  " ",
  ToolExecutingEvent,
  " ",
  "|",
  " ",
  ErrorOccurredEvent,
  ";",
];
var StateEventProcessorInput = [
  "/**\\n* Input event types for StateEventProcessor\\n*/",
  "\\n",
  "type",
  " ",
  StateEventProcessorInput,
  " ",
  "=",
  " ",
  StreamEvent3,
  ";",
];
var stateEventProcessor2 = [
  "/**\\n* stateEventProcessor\\n*\\n* Stateless event transformer: Stream Events → State Events\\n*\\n* Design:\\n* - Does NOT track agent state (that's StateMachine's job)\\n* - Only maintains auxiliary context (timestamps, etc.)\\n* - Emits State Events that StateMachine consumes\\n*\\n* Pattern: (context, input) => [newContext, outputs]\\n*/",
  "\\n",
  "declare",
  " ",
  "const",
  " ",
  stateEventProcessor2,
  ":",
  " ",
  Processor,
  "<",
  StateEventProcessorContext,
  ",",
  " ",
  StateEventProcessorInput,
  ",",
  " ",
  StateEventProcessorOutput,
  ">",
  ";",
];
var stateEventProcessorDef = [
  "/**\\n* StateEvent Processor Definition\\n*\\n* Stateless event transformer: Stream Events → State Events\\n*/",
  "\\n",
  "declare",
  " ",
  "const",
  " ",
  stateEventProcessorDef,
  ":",
  " ",
  ProcessorDefinition,
  "<",
  StateEventProcessorContext,
  ",",
  " ",
  StateEventProcessorInput,
  ",",
  " ",
  StateEventProcessorOutput,
  ">",
  ";",
];
// src/engine/internal/turnTrackerProcessor.ts
import {
  StreamEvent as StreamEvent4,
  AgentMessageEvent,
  TurnRequestEvent,
  TurnResponseEvent,
} from "@agentxjs/types/agent";
var PendingTurn = [
  "/**\\n* Pending turn tracking\\n*/",
  "\\n",
  "interface",
  " ",
  PendingTurn,
  " ",
  "{",
  "\\n\\t",
  turnId,
  ":",
  " ",
  "string",
  ";",
  "\\n\\t",
  messageId,
  ":",
  " ",
  "string",
  ";",
  "\\n\\t",
  "content",
  ":",
  " ",
  "string",
  ";",
  "\\n\\t",
  requestedAt,
  ":",
  " ",
  "number",
  ";",
  "\\n",
  "}",
];
var TurnTrackerState = [
  "/**\\n* TurnTrackerState\\n*\\n* Tracks the current turn state.\\n*/",
  "\\n",
  "interface",
  " ",
  TurnTrackerState,
  " ",
  "{",
  "\\n\\t",
  "/**\\n\\t* Currently pending turn (waiting for response)\\n\\t*/",
  "\\n\\t",
  pendingTurn,
  ":",
  " ",
  PendingTurn,
  " ",
  "|",
  " ",
  "null",
  ";",
  "\\n\\t",
  "/**\\n\\t* Cost per input token (USD)\\n\\t*/",
  "\\n\\t",
  costPerInputToken,
  ":",
  " ",
  "number",
  ";",
  "\\n\\t",
  "/**\\n\\t* Cost per output token (USD)\\n\\t*/",
  "\\n\\t",
  costPerOutputToken,
  ":",
  " ",
  "number",
  ";",
  "\\n",
  "}",
];
var createInitialTurnTrackerState = [
  "/**\\n* Initial state factory for TurnTracker\\n*/",
  "\\n",
  "declare",
  " ",
  "function",
  " ",
  createInitialTurnTrackerState,
  "(",
  ")",
  ":",
  " ",
  TurnTrackerState,
  ";",
];
var TurnTrackerOutput = [
  "/**\\n* Output event types from TurnTracker\\n*/",
  "\\n",
  "type",
  " ",
  TurnTrackerOutput,
  " ",
  "=",
  " ",
  TurnRequestEvent,
  " ",
  "|",
  " ",
  TurnResponseEvent,
  ";",
];
var TurnTrackerInput = [
  "/**\\n* Input event types for TurnTracker\\n* Accepts both Stream and Message layer events\\n*/",
  "\\n",
  "type",
  " ",
  TurnTrackerInput,
  " ",
  "=",
  " ",
  StreamEvent4,
  " ",
  "|",
  " ",
  AgentMessageEvent,
  ";",
];
var turnTrackerProcessor = [
  "/**\\n* turnTrackerProcessor\\n*\\n* Pure Mealy transition function for turn tracking.\\n* Pattern: (state, input) => [newState, outputs]\\n*/",
  "\\n",
  "declare",
  " ",
  "const",
  " ",
  turnTrackerProcessor,
  ":",
  " ",
  Processor,
  "<",
  TurnTrackerState,
  ",",
  " ",
  TurnTrackerInput,
  ",",
  " ",
  TurnTrackerOutput,
  ">",
  ";",
];
var turnTrackerProcessorDef = [
  "/**\\n* TurnTracker Processor Definition\\n*/",
  "\\n",
  "declare",
  " ",
  "const",
  " ",
  turnTrackerProcessorDef,
  ":",
  " ",
  ProcessorDefinition,
  "<",
  TurnTrackerState,
  ",",
  " ",
  TurnTrackerInput,
  ",",
  " ",
  TurnTrackerOutput,
  ">",
  ";",
];
// src/engine/AgentProcessor.ts
import { AgentOutput as AgentOutput3 } from "@agentxjs/types/agent";
var AgentEngineState = [
  "/**\\n* Combined state type for the full agent engine\\n*/",
  "\\n",
  "type",
  " ",
  AgentEngineState,
  " ",
  "=",
  " ",
  "{",
  "\\n\\t",
  messageAssembler,
  ":",
  " ",
  MessageAssemblerState,
  "\\n\\t",
  stateEventProcessor,
  ":",
  " ",
  StateEventProcessorContext,
  "\\n\\t",
  turnTracker,
  ":",
  " ",
  TurnTrackerState,
  "\\n",
  "}",
  ";",
];
var AgentProcessorInput = [
  "/**\\n* Input event type for AgentProcessor\\n*\\n* Accepts:\\n* - StreamEventType: Raw stream events from Driver\\n* - MessageEventType: Re-injected message events (for TurnTracker)\\n*\\n* Note: AgentOutput is used because re-injected events can be any output type\\n*/",
  "\\n",
  "type",
  " ",
  AgentProcessorInput,
  " ",
  "=",
  " ",
  AgentOutput3,
  ";",
];
var AgentProcessorOutput = [
  "/**\\n* Output event type from AgentProcessor\\n*\\n* Produces:\\n* - MessageAssemblerOutput: Assembled message events\\n* - StateEventProcessorOutput: State transition events\\n* - TurnTrackerOutput: Turn analytics events\\n*\\n* Note: StreamEventType is NOT in output - it's passed through by AgentEngine\\n*/",
  "\\n",
  "type",
  " ",
  AgentProcessorOutput,
  " ",
  "=",
  " ",
  MessageAssemblerOutput,
  " ",
  "|",
  " ",
  StateEventProcessorOutput,
  " ",
  "|",
  " ",
  TurnTrackerOutput,
  ";",
];
var agentProcessor = [
  "/**\\n* Combined processor for the full agent engine\\n*\\n* This combines:\\n* - MessageAssembler: Stream → Message events\\n* - StateEventProcessor: Stream → State events\\n* - TurnTracker: Message → Turn events\\n*\\n* Pattern: (state, input) => [newState, outputs]\\n* Key insight: State is means, outputs are the goal (Mealy Machine)\\n*\\n* Note: Raw StreamEvents are NOT output by this processor.\\n* The AgentEngine handles pass-through of original events.\\n*/",
  "\\n",
  "declare",
  " ",
  "const",
  " ",
  agentProcessor,
  ":",
  " ",
  Processor,
  "<",
  AgentEngineState,
  ",",
  " ",
  AgentProcessorInput,
  ",",
  " ",
  AgentProcessorOutput,
  ">",
  ";",
];
var createInitialAgentEngineState = [
  "/**\\n* Initial state factory for the full agent engine\\n*/",
  "\\n",
  "declare",
  " ",
  "const",
  " ",
  createInitialAgentEngineState,
  ":",
  " ",
  "(",
  ")",
  " ",
  "=>",
  " ",
  AgentEngineState,
  ";",
];
export {
  withLogging,
  turnTrackerProcessorDef,
  turnTrackerProcessor,
  stateEventProcessorDef,
  stateEventProcessor2 as stateEventProcessor,
  messageAssemblerProcessorDef,
  messageAssemblerProcessor,
  mapOutput,
  identityProcessor,
  filterProcessor,
  createMealyMachine,
  createInitialTurnTrackerState,
  createInitialStateEventProcessorContext,
  createInitialMessageAssemblerState,
  createInitialAgentEngineState,
  createAgent,
  combineProcessors,
  combineInitialStates,
  chainProcessors,
  agentProcessor,
  TurnTrackerState,
  TurnTrackerOutput,
  TurnTrackerInput,
  Store,
  StateEventProcessorOutput,
  StateEventProcessorInput,
  StateEventProcessorContext,
  SourceDefinition,
  Source,
  SinkDefinition,
  Sink,
  ProcessorResult,
  ProcessorDefinition,
  Processor,
  PendingTurn,
  PendingContent,
  MessageAssemblerState,
  MessageAssemblerOutput,
  MessageAssemblerInput,
  MemoryStore,
  MealyMachine,
  CreateAgentOptions2 as CreateAgentOptions,
  AgentStateMachine,
  AgentProcessorOutput,
  AgentProcessorInput,
  AgentEngineState,
  AgentEngine2 as AgentEngine,
};
