/**
 * Conversation Interrupted State Event (L2: State Layer)
 *
 * State transition: (Any conversation state) → Idle
 *
 * Emitted when a conversation is interrupted by user or system.
 * This signals that the current operation should be stopped immediately.
 *
 * Generated by StateEventProcessor when it receives an interrupted stream event.
 */

import type { StateEvent } from "./StateEvent";

export interface ConversationInterruptedStateEvent extends StateEvent {
  type: "conversation_interrupted";

  /**
   * Event data
   */
  data: {
    /**
     * Reason for interruption
     *
     * - "user_interrupt": User manually stopped (e.g., clicked Stop button)
     * - "timeout": Operation exceeded configured time limit
     * - "error": System error forced interruption
     * - "system": System-initiated interruption
     */
    reason: "user_interrupt" | "timeout" | "error" | "system";
  };
}
