/**
 * SessionRecord - Storage schema for Session persistence
 *
 * Pure data type representing a session (external user-facing view) in storage.
 * Session wraps Image for external concerns:
 * - User ownership (userId)
 * - UI display (title, metadata)
 *
 * Part of Docker-style layered architecture:
 * Definition → build → Image → run → Agent
 *                        ↓
 *                    Session (external wrapper)
 */

/**
 * Session storage record
 */
export interface SessionRecord {
  /**
   * Unique session identifier
   */
  sessionId: string;

  /**
   * Owner user identifier
   */
  userId: string;

  /**
   * Associated image identifier (frozen runtime snapshot)
   */
  imageId: string;

  /**
   * Display title (can be auto-generated by AI summary)
   */
  title: string | null;

  /**
   * Creation timestamp
   */
  createdAt: Date;

  /**
   * Last update timestamp
   */
  updatedAt: Date;
}
