/**
 * Agent State Events
 *
 * State transition events for Agent lifecycle and conversation flow.
 * Generated by AgentEngine's Mealy Machine from stream events.
 */

import type { RuntimeEvent } from "../../RuntimeEvent";

/**
 * Base StateEvent
 */
export interface StateEvent<T extends string = string, D = unknown> extends RuntimeEvent<T, D> {
  source: "agent";
  category: "state";
  intent: "notification";
}

// ============================================================================
// Agent Lifecycle States
// ============================================================================

/**
 * AgentInitializingEvent - Agent is initializing
 */
export interface AgentInitializingEvent extends StateEvent<"agent_initializing"> {
  data: {
    agentId: string;
  };
}

/**
 * AgentReadyEvent - Agent is ready to receive messages
 */
export interface AgentReadyEvent extends StateEvent<"agent_ready"> {
  data: {
    agentId: string;
  };
}

/**
 * AgentDestroyedEvent - Agent has been destroyed
 */
export interface AgentDestroyedEvent extends StateEvent<"agent_destroyed"> {
  data: {
    agentId: string;
    reason?: string;
  };
}

// ============================================================================
// Conversation States
// ============================================================================

/**
 * ConversationQueuedEvent - Message queued for processing
 */
export interface ConversationQueuedEvent extends StateEvent<"conversation_queued"> {
  data: {
    messageId: string;
  };
}

/**
 * ConversationStartEvent - Conversation started
 */
export interface ConversationStartEvent extends StateEvent<"conversation_start"> {
  data: {
    messageId: string;
  };
}

/**
 * ConversationThinkingEvent - Agent is thinking
 */
export interface ConversationThinkingEvent extends StateEvent<"conversation_thinking"> {
  data: Record<string, never>;
}

/**
 * ConversationRespondingEvent - Agent is responding
 */
export interface ConversationRespondingEvent extends StateEvent<"conversation_responding"> {
  data: Record<string, never>;
}

/**
 * ConversationEndEvent - Conversation ended
 */
export interface ConversationEndEvent extends StateEvent<"conversation_end"> {
  data: {
    reason: "completed" | "interrupted" | "error";
  };
}

/**
 * ConversationInterruptedEvent - Conversation interrupted
 */
export interface ConversationInterruptedEvent extends StateEvent<"conversation_interrupted"> {
  data: {
    reason: string;
  };
}

// ============================================================================
// Tool States
// ============================================================================

/**
 * ToolPlannedEvent - Tool use planned
 */
export interface ToolPlannedEvent extends StateEvent<"tool_planned"> {
  data: {
    toolId: string;
    toolName: string;
  };
}

/**
 * ToolExecutingEvent - Tool is executing
 */
export interface ToolExecutingEvent extends StateEvent<"tool_executing"> {
  data: {
    toolId: string;
    toolName: string;
    input: Record<string, unknown>;
  };
}

/**
 * ToolCompletedEvent - Tool execution completed
 */
export interface ToolCompletedEvent extends StateEvent<"tool_completed"> {
  data: {
    toolId: string;
    toolName: string;
    result: unknown;
  };
}

/**
 * ToolFailedEvent - Tool execution failed
 */
export interface ToolFailedEvent extends StateEvent<"tool_failed"> {
  data: {
    toolId: string;
    toolName: string;
    error: string;
  };
}

// ============================================================================
// Error State
// ============================================================================

/**
 * ErrorOccurredEvent - Error occurred during processing
 */
export interface ErrorOccurredEvent extends StateEvent<"error_occurred"> {
  data: {
    code: string;
    message: string;
    recoverable: boolean;
  };
}

// ============================================================================
// Union Type
// ============================================================================

/**
 * AgentStateEvent - All agent state events
 */
export type AgentStateEvent =
  // Lifecycle
  | AgentInitializingEvent
  | AgentReadyEvent
  | AgentDestroyedEvent
  // Conversation
  | ConversationQueuedEvent
  | ConversationStartEvent
  | ConversationThinkingEvent
  | ConversationRespondingEvent
  | ConversationEndEvent
  | ConversationInterruptedEvent
  // Tool
  | ToolPlannedEvent
  | ToolExecutingEvent
  | ToolCompletedEvent
  | ToolFailedEvent
  // Error
  | ErrorOccurredEvent;

/**
 * Type guard: is this a state event?
 */
export function isStateEvent(event: RuntimeEvent): event is AgentStateEvent {
  return event.source === "agent" && event.category === "state";
}
