/**
 * Session - External wrapper for user-facing conversation management
 *
 * Part of Docker-style layered architecture:
 * Definition → build → Image → run → Agent
 *                        ↓
 *                    Session (external wrapper)
 *
 * Session is AgentX-specific (Docker doesn't have this).
 * It wraps Image for external concerns:
 * - User ownership (userId)
 * - UI display (title, metadata)
 * - External system integration
 *
 * Image is internal (frozen runtime state).
 * Session is external (user-facing view).
 *
 * @example
 * ```typescript
 * // Create session for a user
 * const session = await agentx.sessions.create(imageId, userId);
 *
 * // Resume agent from session's image
 * const agent = await session.resume();
 *
 * // Continue conversation
 * await agent.receive("Hello again!");
 *
 * // Fork session (creates new image with current messages)
 * const forkedSession = await session.fork();
 *
 * // Update title
 * await session.setTitle("Discussion about API design");
 * ```
 */

import type { Agent } from "~/ecosystem/agent/Agent";
import type { Message } from "~/ecosystem/agent/message/Message";

/**
 * Session represents a user-facing conversation context
 */
export interface Session {
  /**
   * Unique session identifier
   */
  readonly sessionId: string;

  /**
   * Owner user ID
   */
  readonly userId: string;

  /**
   * Associated image ID (frozen runtime snapshot)
   */
  readonly imageId: string;

  /**
   * Display title (can be auto-generated by AI summary)
   */
  readonly title: string | null;

  /**
   * Session creation timestamp (Unix ms)
   */
  readonly createdAt: number;

  /**
   * Last update timestamp (Unix ms)
   */
  readonly updatedAt: number;

  /**
   * Resume an agent from this session's image
   *
   * Creates a new agent instance from the associated image,
   * which contains the frozen definition, config, and messages.
   *
   * @param options - Optional configuration
   * @param options.containerId - Container to run in (defaults to auto-created container)
   * @returns Agent instance ready to continue the conversation
   */
  resume(options?: { containerId?: string }): Promise<Agent>;

  /**
   * Fork this session to create a new branch
   *
   * Creates a new Image with current messages copied,
   * and a new Session pointing to the forked image.
   *
   * @returns New forked session
   */
  fork(): Promise<Session>;

  /**
   * Update the session title
   *
   * @param title - New title (can be AI-generated summary)
   */
  setTitle(title: string): Promise<void>;

  /**
   * Collect messages from an agent to this session
   *
   * Registers internal presenter to capture all message events
   * (user, assistant, tool_call, tool_result) and persist them.
   *
   * @param agent - The agent to collect messages from
   */
  collect(agent: Agent): void;

  /**
   * Get all messages for this session
   *
   * @returns Array of messages in chronological order
   */
  getMessages(): Promise<Message[]>;
}
