/**
 * SessionRecord - Storage schema for Session persistence
 *
 * Session belongs to a Container and references an Image.
 *
 * Architecture:
 * ```
 * Container
 * └── Session (conversation context)
 *     └── Messages
 * ```
 *
 * Part of Docker-style layered architecture:
 * Definition → build → Image → run → Agent
 *                        ↓
 *                    Session (runtime context)
 */

/**
 * Session storage record
 */
export interface SessionRecord {
  /**
   * Unique session identifier
   */
  sessionId: string;

  /**
   * Container this session belongs to
   */
  containerId: string;

  /**
   * Associated image identifier (frozen runtime snapshot)
   */
  imageId: string;

  /**
   * Display title (can be auto-generated by AI summary)
   */
  title: string | null;

  /**
   * Creation timestamp (Unix milliseconds)
   */
  createdAt: number;

  /**
   * Last update timestamp (Unix milliseconds)
   */
  updatedAt: number;
}
