/**
 * EnvironmentEvent - All events perceived from external world
 *
 * Architecture:
 * ```
 * EnvironmentEvent (all external perceptions, with turnId)
 * │
 * ├── DriveableEvent (can drive Agent)
 * │   │   - Receptor outputs this (with turnId)
 * │   │   - Driver transforms to AgentStreamEvent (adds agentId)
 * │   └── MessageStartEvent, TextDeltaEvent, ToolCallEvent...
 * │
 * └── ConnectionEvent (network status only, does not drive Agent)
 *     └── ConnectedEvent, DisconnectedEvent, ReconnectingEvent
 * ```
 *
 * Key Design:
 * - All EnvironmentEvents have turnId for routing
 * - turnId correlates all events within a single turn (user message + assistant response cycle)
 * - Driver uses turnId to filter events for its Agent
 *
 * Isomorphic Design:
 * - Same event types work in both NodeEcosystem and RemoteEcosystem
 * - In NodeEcosystem: ClaudeReceptor emits DriveableEvents
 * - In RemoteEcosystem: NetworkReceptor receives events via WebSocket
 */

import type { SystemEvent } from "../base";
import type { DriveableEvent } from "./DriveableEvent";
import type { ConnectionEvent } from "./ConnectionEvent";

/**
 * BaseEnvironmentEvent - Common structure for all environment events
 *
 * All environment events include turnId for routing to the correct Agent/Driver.
 */
export interface BaseEnvironmentEvent<T extends string = string, D = unknown>
  extends SystemEvent<T, D> {
  /**
   * Turn ID for correlating events within a single turn
   *
   * A turn = one user message + assistant response cycle.
   * Generated by Agent when receiving user input, attached to all response events.
   * Driver uses this to filter events that belong to its Agent's current turn.
   */
  readonly turnId: string;
}

/**
 * EnvironmentEvent - Union of all external world events
 */
export type EnvironmentEvent = DriveableEvent | ConnectionEvent;

/**
 * Type guard: is this event driveable (can drive Agent)?
 */
export function isDriveableEvent(event: EnvironmentEvent): event is DriveableEvent {
  const connectionTypes = ["connected", "disconnected", "reconnecting"];
  return !connectionTypes.includes(event.type);
}

/**
 * Type guard: is this a connection event?
 */
export function isConnectionEvent(event: EnvironmentEvent): event is ConnectionEvent {
  const connectionTypes = ["connected", "disconnected", "reconnecting"];
  return connectionTypes.includes(event.type);
}
