/**
 * Session - Conversation context with resume capability
 *
 * Session is a history container - it records messages and helps restore conversations.
 * Sessions can persist across multiple message exchanges
 * and support resuming agents with conversation history.
 *
 * @example
 * ```typescript
 * // Get existing session
 * const session = await agentx.sessions.get(sessionId);
 *
 * // Resume agent with conversation history
 * const agent = await session.resume();
 *
 * // Continue conversation
 * await agent.receive("Hello again!");
 *
 * // Update title (e.g., AI-generated summary)
 * await session.setTitle("Discussion about API design");
 * ```
 */

import type { Agent } from "~/agent/Agent";

/**
 * Session represents a conversation context
 */
export interface Session {
  /**
   * Unique session identifier
   */
  readonly sessionId: string;

  /**
   * Associated agent ID
   */
  readonly agentId: string;

  /**
   * Display title (can be auto-generated by AI summary)
   */
  readonly title: string | null;

  /**
   * Session creation timestamp (Unix ms)
   */
  readonly createdAt: number;

  /**
   * Last update timestamp (Unix ms)
   */
  readonly updatedAt: number;

  /**
   * Resume an agent with this session's conversation history
   *
   * Creates a new agent instance with the stored definition and config,
   * then loads the conversation history from storage.
   *
   * @returns Agent instance ready to continue the conversation
   */
  resume(): Promise<Agent>;

  /**
   * Update the session title
   *
   * @param title - New title (can be AI-generated summary)
   */
  setTitle(title: string): Promise<void>;
}
