import type { TextPart } from "./parts/TextPart";
import type { ThinkingPart } from "./parts/ThinkingPart";
import type { ToolCallPart } from "./parts/ToolCallPart";
import type { FilePart } from "./parts/FilePart";
import type { TokenUsage } from "~/llm/TokenUsage";

/**
 * Assistant Message
 *
 * Message generated by the AI assistant.
 * Can contain text, thinking process, tool calls, or files.
 */
export interface AssistantMessage {
  /** Unique identifier */
  id: string;

  /** Message role */
  role: "assistant";

  /** Message subtype for serialization */
  subtype: "assistant";

  /** Message content - can be simple string or array of parts */
  content: string | Array<TextPart | ThinkingPart | ToolCallPart | FilePart>;

  /** When this message was created (Unix timestamp in milliseconds) */
  timestamp: number;

  /** Parent message ID for threading (optional) */
  parentId?: string;

  /** Token usage for this AI response (optional) */
  usage?: TokenUsage;
}
