/**
 * Agent State Events
 *
 * Events that trigger AgentState transitions.
 * Generated by MealyMachine from stream events.
 *
 * Note: These are NOT "state" events - they are events that AFFECT state.
 * Agent lifecycle events (initializing, ready, destroyed) belong to Runtime domain.
 */

import type { AgentEvent } from "../AgentEvent";

/**
 * Base StateEvent
 */
export interface StateEvent<T extends string = string, D = unknown> extends AgentEvent<T, D> {}

// ============================================================================
// Conversation Events (affect AgentState)
// ============================================================================

/**
 * ConversationQueuedEvent - Message queued for processing
 */
export interface ConversationQueuedEvent extends StateEvent<"conversation_queued"> {
  data: {
    messageId: string;
  };
}

/**
 * ConversationStartEvent - Conversation started
 */
export interface ConversationStartEvent extends StateEvent<"conversation_start"> {
  data: {
    messageId: string;
  };
}

/**
 * ConversationThinkingEvent - Agent is thinking
 */
export interface ConversationThinkingEvent extends StateEvent<"conversation_thinking"> {
  data: Record<string, never>;
}

/**
 * ConversationRespondingEvent - Agent is responding
 */
export interface ConversationRespondingEvent extends StateEvent<"conversation_responding"> {
  data: Record<string, never>;
}

/**
 * ConversationEndEvent - Conversation ended
 */
export interface ConversationEndEvent extends StateEvent<"conversation_end"> {
  data: {
    reason: "completed" | "interrupted" | "error";
  };
}

/**
 * ConversationInterruptedEvent - Conversation interrupted
 */
export interface ConversationInterruptedEvent extends StateEvent<"conversation_interrupted"> {
  data: {
    reason: string;
  };
}

// ============================================================================
// Tool Events (affect AgentState)
// ============================================================================

/**
 * ToolPlannedEvent - Tool use planned
 */
export interface ToolPlannedEvent extends StateEvent<"tool_planned"> {
  data: {
    toolId: string;
    toolName: string;
  };
}

/**
 * ToolExecutingEvent - Tool is executing
 */
export interface ToolExecutingEvent extends StateEvent<"tool_executing"> {
  data: {
    toolId: string;
    toolName: string;
    input: Record<string, unknown>;
  };
}

/**
 * ToolCompletedEvent - Tool execution completed
 */
export interface ToolCompletedEvent extends StateEvent<"tool_completed"> {
  data: {
    toolId: string;
    toolName: string;
    result: unknown;
  };
}

/**
 * ToolFailedEvent - Tool execution failed
 */
export interface ToolFailedEvent extends StateEvent<"tool_failed"> {
  data: {
    toolId: string;
    toolName: string;
    error: string;
  };
}

// ============================================================================
// Error Events (affect AgentState)
// ============================================================================

/**
 * ErrorOccurredEvent - Error occurred during processing
 */
export interface ErrorOccurredEvent extends StateEvent<"error_occurred"> {
  data: {
    code: string;
    message: string;
    recoverable: boolean;
    category?: string;
  };
}

/**
 * Alias for ErrorOccurredEvent (legacy compatibility)
 */
export type AgentErrorOccurredEvent = ErrorOccurredEvent;

// ============================================================================
// Union Type
// ============================================================================

/**
 * AgentStateEvent - Events that affect AgentState
 */
export type AgentStateEvent =
  // Conversation
  | ConversationQueuedEvent
  | ConversationStartEvent
  | ConversationThinkingEvent
  | ConversationRespondingEvent
  | ConversationEndEvent
  | ConversationInterruptedEvent
  // Tool
  | ToolPlannedEvent
  | ToolExecutingEvent
  | ToolCompletedEvent
  | ToolFailedEvent
  // Error
  | ErrorOccurredEvent;

/**
 * Type guard: is this a state event?
 */
export function isStateEvent(event: AgentEvent): event is AgentStateEvent {
  const stateTypes = [
    "conversation_queued", "conversation_start", "conversation_thinking",
    "conversation_responding", "conversation_end", "conversation_interrupted",
    "tool_planned", "tool_executing", "tool_completed", "tool_failed",
    "error_occurred"
  ];
  return stateTypes.includes(event.type);
}
