/**
 * SessionRecord - Storage schema for Session persistence
 *
 * Pure data type representing a session (conversation context) in storage.
 * Session is a history container - it records messages and helps restore conversations.
 */

/**
 * Session storage record
 */
export interface SessionRecord {
  /**
   * Unique session identifier
   */
  sessionId: string;

  /**
   * Associated agent identifier
   */
  agentId: string;

  /**
   * Display title (can be auto-generated by AI summary)
   */
  title: string | null;

  /**
   * Creation timestamp
   */
  createdAt: Date;

  /**
   * Last update timestamp
   */
  updatedAt: Date;
}
